name: xoecollect
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  awesome_dialog: ^3.1.0
  blue_thermal_printer: ^1.2.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.2
  # cloud_firestore: ^4.5.2
  country_code_picker: ^3.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  custom_pin_screen: ^0.5.0
  easy_localization: ^3.0.1
  faker: ^2.1.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_esc_pos_utils: ^1.0.0
  flutter_image_compress: ^2.0.1
  flutter_screenutil: ^5.7.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.3
  flutter_zoom_drawer: ^3.0.4+1
  fluttertoast: ^8.2.1
  get_it: ^7.6.4
  go_router: ^6.5.7
  google_fonts: ^4.0.3
  http: ^0.13.5
  image_picker: ^0.8.7+4
  intl: ^0.18.0
  intl_phone_number_input: ^0.7.0+2
  logger: ^1.3.0
  lottie: ^2.3.2
  modal_bottom_sheet: ^3.0.0-pre
  open_file: ^3.3.2
  pdf: ^3.5.0
  pin_plus_keyboard: ^2.0.6
  pinput: ^3.0.1
  printing: ^5.10.4
  share_plus: ^7.1.0
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  sticky_az_list: ^0.0.5
  # syncfusion_flutter_charts: ^23.1.36
  sunmi_printer_plus: ^2.1.2
  url_launcher: ^6.1.14
  uuid: ^3.0.7

dev_dependencies:
  # flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  rename: ^2.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/icons/
    - assets/animations/
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - .env
  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/EuclidCircularA-Regular.ttf
        - asset: assets/fonts/EuclidCircularA-Medium.ttf

        - asset: assets/fonts/EuclidCircularA-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/EuclidCircularA-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/EuclidCircularA-Italic.ttf
          style: italic

        - asset: assets/fonts/EuclidCircularA-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
